qlib_init:
  provider_uri: "~/.qlib/crypto_data"
  region: crypto
  custom_ops:
    - class: FundingZScore
      module_path: qlib_crypto.contrib.ops.crypto_ops
    - class: BasisPct
      module_path: qlib_crypto.contrib.ops.crypto_ops
    - class: OIRatio
      module_path: qlib_crypto.contrib.ops.crypto_ops

market: &market all
benchmark: &benchmark BINANCE_BTCUSDT

data_handler_config: &data_handler_config
  start_time: 2020-01-01
  end_time: 2024-12-31
  fit_start_time: 2020-01-01
  fit_end_time: 2022-12-31
  instruments: *market
  infer_processors: []
  learn_processors:
    - class: DropnaLabel
    - class: CSZScoreNorm
      kwargs:
        fields_group: label

port_analysis_config: &port_analysis_config
  strategy:
    class: CryptoTopkStrategy
    module_path: qlib_crypto.contrib.strategy.signal_strategy
    kwargs:
      signal: <PRED>
      topk: 30
      n_drop: 5
      only_tradable: true
      hold_thresh: 0
  backtest:
    start_time: 2023-01-01
    end_time: 2024-12-31
    account: 10000000
    benchmark: *benchmark
    exchange_kwargs:
      deal_price: close
      open_cost: 0.0005
      close_cost: 0.0005
      min_cost: 0
      limit_threshold: null


task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      colsample_bytree: 0.8
      learning_rate: 0.05
      subsample: 0.8
      lambda_l1: 200.0
      lambda_l2: 300.0
      max_depth: 8
      num_leaves: 128
      num_threads: 8

  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158Crypto
        module_path: qlib_crypto.contrib.data.handler
        kwargs: *data_handler_config
      segments:
        train: [2020-01-01, 2022-12-31]
        valid: [2023-01-01, 2023-12-31]
        test: [2024-01-01, 2024-12-31]

  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        model: <MODEL>
        dataset: <DATASET>

    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: false
        ann_scaler: 365

    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config
